import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import VantaNetBackground from "@/components/ui/Vantabg";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
// import About from "@/app/pages/about/page"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // {/* remove black after using vantajs and use bg-transparent*/}

        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        {/* <VantaNetBackground options={{mouseControls:true,touchControls:true}}> */}
         <Navbar/>
         
         {/* <About/> */}
          {children}
   
          <Footer/>
        {/* </VantaNetBackground> */}
      </body>
    </html>
  );
}
